# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Status Lane' do
pod 'RSKImageCropper'
source 'https://github.com/CocoaPods/Specs.git'
pod 'libPhoneNumber-iOS', '~> 0.8'
end

target 'Status LaneTests' do

end

